### ISSUE TITLE
adding Irish whistle

### ISSUE THREAD

**Issue by cal-invisible** [amunn/recorder-fingering#1]
I could be good to add Irish whistle fingerings. Here is a first proposal. It is not fully functional because I did not checked all the fingerings, only the one I need to play (I am beginning).

**Comment by amunn** [comment]
Thanks for the suggestion to add the tin whistle. I've implemented the code (v1.2)  differently from your suggestions, so that the fingerings can use just the expected 6 holes.

**Comment by cal-invisible** [comment]
thank you, that is far better than what I implemented.
